In [9]:
import pandas as pd
# read in as dataframe type
map_df = pd.read_csv('Dataset/location_5.csv')
map_df

,Unnamed: 0,locationId,Latitude,Longitude,Location,Typing,Business_Time,buildingID,FacilityType,stationNewNum,stationUpperElec,contractCapacity,budget
0,0,50840,56.488382,-3.014353,Ardler Complex,leisure,0800-2000,6,4,10,100,175,45
1,1,50911,56.467790,-2.873580,Queen Street Car Park,coffee,0800-1700,13,1,10,100,222,43
2,2,50692,56.482148,-3.024697,Dundee Ice Arena,leisure,1000-1600,3,4,10,100,173,40
3,3,50841,56.470163,-2.920664,Brington Place Sheltered Housing,grocery,0800-2200,2,2,10,100,415,45
4,4,51199,56.460112,-2.975760,Dundee House,restaurant,1200-2100,1,3,10,100,204,43
5,5,50269,56.482222,-2.935812,Dundee East District Housing Office,grocery,0700-2000,12,2,10,100,155,45
6,6,51198,56.460164,-2.975911,Dundee House,restaurant,0800-2400,5,3,10,100,212,39
7,7,50263,56.489722,-2.917516,Whitfield Centre,grocery,0800-2000,11,2,10,100,149,40
8,8,50240,56.461541,-2.966639,Gellatly Street Car Park,coffee,1000-1600,17,1,10,100,217,47
9,9,50349,56.456726,-2.973511,Greenmarket Car Park,restaurant,1300-2200,7,3,10,100,394,30
10,10,51200,56.460054,-2.975608,Dundee House,leisure,1200-2400,15,4,10,100,205,35
11,11,50909,56.459078,-2.977268,South Tay Street,leisure,0900-1700,8,4,10,100,237,34
12,12,50230,56.472968,-3.002456,Marchbanks,grocery,0800-2100,0,2,10,100,236,30
13,13,50266,56.465481,-3.035287,Menziehill House,grocery,0700-2200,10,2,10,100,273,37
14,14,50261,56.463943,-2.992653,Mitchell Street Centre,restaurant,1600-2300,9,3,10,100,360,33
15,15,50675,56.463556,-2.962498,Olympia Multi-Storey Car Park,grocery,0800-2000,18,2,10,100,345,30
16,16,50267,56.496018,-2.947257,Social Work Building,restaurant,1400-2200,14,3,10,100,276,37
17,17,50338,56.496016,-2.947476,Social Work Building,restaurant,1700-2400,16,3,10,100,276,33
18,18,51087,56.467775,-2.873361,Queen Street Car Park,coffee,0800-1800,4,1,10,100,183,44
19,19,50268,56.473272,-3.011615,"Housing Office West, Dundee",coffee,1000-1800,19,1,10,100,343,40

In [10]:
# regard locationID as key and FacilityType as value
map_dict = dict(zip(map_df['locationId'], map_df['FacilityType']))

In [11]:
# read in as dataframe type
charg_df = pd.read_csv('Dataset/charging_data_2_move.csv') 
# read in as dataframe type
charg_df = pd.read_csv('Dataset/charging_data_2_move.csv')   
    
# create a new list (facilityType) to charg_df
add_facility_list = []
for row in charg_df['locationId']:
	# get the corresponding facilityType of current row
	facility_type = map_dict[row]
	# append to add_facility_list
	add_facility_list.append(facility_type)

add_facility_list
# create a new column to record corresponding facilityType of each row
charg_df['facilityType'] = add_facility_list
group_df = charg_df.groupby(['userId', 'facilityType'])
# display(group_df.apply(lambda x: x.reset_index(drop=True)))

user_facility_times_dic = {}

for key, item in group_df:
	userId = key[0] # the first key value is userId
	facilityType = key[1] # second key value is facilityType

	# assign a default value '{}' only if userId hasn't be a key yet.
	user_facility_times_dic.setdefault(userId, {})

	# df.shape[0] is the number of rows in a dataframe
	# record item.shape[0] (the times of userId charges at facilityType)
	user_facility_times_dic[userId][facilityType] = item.shape[0]

In [12]:
user_facility_perc_dic = {}
for key, value in user_facility_times_dic.items():
    total = sum(value.values())
    user_facility_perc_dic[str(key)] = {str(type):times/total for type, times in value.items()}

In [13]:
import json

with open('user_facility_perc_dic.json', 'w') as f:
    json.dump(user_facility_perc_dic, f)

In [19]:
import itertools

# 定义要生成排列组合的列表
facility_percent = [0, 0.2, 0.4, 0.6, 0.8, 1]
time_difference = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
incentive = [1, 2, 3, 4]

# 生成所有可能的排列组合
combinations = list(itertools.product(facility_percent, time_difference, incentive))

# 创建一个空字典来存储 q_table 表
q_table = {} 

# 将所有排列组合作为字典的键，值初始化为0
for combo in combinations:
    q_table[combo] = 0

# 输出 q_table 表
print(q_table)

{(0, 1, 1): 0, (0, 1, 2): 0, (0, 1, 3): 0, (0, 1, 4): 0, (0, 2, 1): 0, (0, 2, 2): 0, (0, 2, 3): 0, (0, 2, 4): 0, (0, 3, 1): 0, (0, 3, 2): 0, (0, 3, 3): 0, (0, 3, 4): 0, (0, 4, 1): 0, (0, 4, 2): 0, (0, 4, 3): 0, (0, 4, 4): 0, (0, 5, 1): 0, (0, 5, 2): 0, (0, 5, 3): 0, (0, 5, 4): 0, (0, 6, 1): 0, (0, 6, 2): 0, (0, 6, 3): 0, (0, 6, 4): 0, (0, 7, 1): 0, (0, 7, 2): 0, (0, 7, 3): 0, (0, 7, 4): 0, (0, 8, 1): 0, (0, 8, 2): 0, (0, 8, 3): 0, (0, 8, 4): 0, (0, 9, 1): 0, (0, 9, 2): 0, (0, 9, 3): 0, (0, 9, 4): 0, (0, 10, 1): 0, (0, 10, 2): 0, (0, 10, 3): 0, (0, 10, 4): 0, (0, 11, 1): 0, (0, 11, 2): 0, (0, 11, 3): 0, (0, 11, 4): 0, (0, 12, 1): 0, (0, 12, 2): 0, (0, 12, 3): 0, (0, 12, 4): 0, (0, 13, 1): 0, (0, 13, 2): 0, (0, 13, 3): 0, (0, 13, 4): 0, (0, 14, 1): 0, (0, 14, 2): 0, (0, 14, 3): 0, (0, 14, 4): 0, (0, 15, 1): 0, (0, 15, 2): 0, (0, 15, 3): 0, (0, 15, 4): 0, (0, 16, 1): 0, (0, 16, 2): 0, (0, 16, 3): 0, (0, 16, 4): 0, (0, 17, 1): 0, (0, 17, 2): 0, (0, 17, 3): 0, (0, 17, 4): 0, (0, 18, 1): 0, (0, 18, 2): 0, (0, 18, 3): 0, (0, 18, 4): 0, (0, 19, 1): 0, (0, 19, 2): 0, (0, 19, 3): 0, (0, 19, 4): 0, (0, 20, 1): 0, (0, 20, 2): 0, (0, 20, 3): 0, (0, 20, 4): 0, (0, 21, 1): 0, (0, 21, 2): 0, (0, 21, 3): 0, (0, 21, 4): 0, (0, 22, 1): 0, (0, 22, 2): 0, (0, 22, 3): 0, (0, 22, 4): 0, (0, 23, 1): 0, (0, 23, 2): 0, (0, 23, 3): 0, (0, 23, 4): 0, (0.2, 1, 1): 0, (0.2, 1, 2): 0, (0.2, 1, 3): 0, (0.2, 1, 4): 0, (0.2, 2, 1): 0, (0.2, 2, 2): 0, (0.2, 2, 3): 0, (0.2, 2, 4): 0, (0.2, 3, 1): 0, (0.2, 3, 2): 0, (0.2, 3, 3): 0, (0.2, 3, 4): 0, (0.2, 4, 1): 0, (0.2, 4, 2): 0, (0.2, 4, 3): 0, (0.2, 4, 4): 0, (0.2, 5, 1): 0, (0.2, 5, 2): 0, (0.2, 5, 3): 0, (0.2, 5, 4): 0, (0.2, 6, 1): 0, (0.2, 6, 2): 0, (0.2, 6, 3): 0, (0.2, 6, 4): 0, (0.2, 7, 1): 0, (0.2, 7, 2): 0, (0.2, 7, 3): 0, (0.2, 7, 4): 0, (0.2, 8, 1): 0, (0.2, 8, 2): 0, (0.2, 8, 3): 0, (0.2, 8, 4): 0, (0.2, 9, 1): 0, (0.2, 9, 2): 0, (0.2, 9, 3): 0, (0.2, 9, 4): 0, (0.2, 10, 1): 0, (0.2, 10, 2): 0, (0.2, 10, 3): 0, (0.2, 10, 4): 0, (0.2, 11, 1): 0, (0.2, 11, 2): 0, (0.2, 11, 3): 0, (0.2, 11, 4): 0, (0.2, 12, 1): 0, (0.2, 12, 2): 0, (0.2, 12, 3): 0, (0.2, 12, 4): 0, (0.2, 13, 1): 0, (0.2, 13, 2): 0, (0.2, 13, 3): 0, (0.2, 13, 4): 0, (0.2, 14, 1): 0, (0.2, 14, 2): 0, (0.2, 14, 3): 0, (0.2, 14, 4): 0, (0.2, 15, 1): 0, (0.2, 15, 2): 0, (0.2, 15, 3): 0, (0.2, 15, 4): 0, (0.2, 16, 1): 0, (0.2, 16, 2): 0, (0.2, 16, 3): 0, (0.2, 16, 4): 0, (0.2, 17, 1): 0, (0.2, 17, 2): 0, (0.2, 17, 3): 0, (0.2, 17, 4): 0, (0.2, 18, 1): 0, (0.2, 18, 2): 0, (0.2, 18, 3): 0, (0.2, 18, 4): 0, (0.2, 19, 1): 0, (0.2, 19, 2): 0, (0.2, 19, 3): 0, (0.2, 19, 4): 0, (0.2, 20, 1): 0, (0.2, 20, 2): 0, (0.2, 20, 3): 0, (0.2, 20, 4): 0, (0.2, 21, 1): 0, (0.2, 21, 2): 0, (0.2, 21, 3): 0, (0.2, 21, 4): 0, (0.2, 22, 1): 0, (0.2, 22, 2): 0, (0.2, 22, 3): 0, (0.2, 22, 4): 0, (0.2, 23, 1): 0, (0.2, 23, 2): 0, (0.2, 23, 3): 0, (0.2, 23, 4): 0, (0.4, 1, 1): 0, (0.4, 1, 2): 0, (0.4, 1, 3): 0, (0.4, 1, 4): 0, (0.4, 2, 1): 0, (0.4, 2, 2): 0, (0.4, 2, 3): 0, (0.4, 2, 4): 0, (0.4, 3, 1): 0, (0.4, 3, 2): 0, (0.4, 3, 3): 0, (0.4, 3, 4): 0, (0.4, 4, 1): 0, (0.4, 4, 2): 0, (0.4, 4, 3): 0, (0.4, 4, 4): 0, (0.4, 5, 1): 0, (0.4, 5, 2): 0, (0.4, 5, 3): 0, (0.4, 5, 4): 0, (0.4, 6, 1): 0, (0.4, 6, 2): 0, (0.4, 6, 3): 0, (0.4, 6, 4): 0, (0.4, 7, 1): 0, (0.4, 7, 2): 0, (0.4, 7, 3): 0, (0.4, 7, 4): 0, (0.4, 8, 1): 0, (0.4, 8, 2): 0, (0.4, 8, 3): 0, (0.4, 8, 4): 0, (0.4, 9, 1): 0, (0.4, 9, 2): 0, (0.4, 9, 3): 0, (0.4, 9, 4): 0, (0.4, 10, 1): 0, (0.4, 10, 2): 0, (0.4, 10, 3): 0, (0.4, 10, 4): 0, (0.4, 11, 1): 0, (0.4, 11, 2): 0, (0.4, 11, 3): 0, (0.4, 11, 4): 0, (0.4, 12, 1): 0, (0.4, 12, 2): 0, (0.4, 12, 3): 0, (0.4, 12, 4): 0, (0.4, 13, 1): 0, (0.4, 13, 2): 0, (0.4, 13, 3): 0, (0.4, 13, 4): 0, (0.4, 14, 1): 0, (0.4, 14, 2): 0, (0.4, 14, 3): 0, (0.4, 14, 4): 0, (0.4, 15, 1): 0, (0.4, 15, 2): 0, (0.4, 15, 3): 0, (0.4, 15, 4): 0, (0.4, 16, 1): 0, (0.4, 16, 2): 0, (0.4, 16, 3): 0, (0.4, 16, 4): 0, (0.4, 17, 1): 0, (0.4, 17, 2): 0, (0.4, 17, 3): 0, (0.4, 17, 4): 0, (0.4, 18, 1): 0, (0.4, 18, 2): 0, (0.4, 18, 3): 0, (0.4, 18, 4): 0, (0.4, 19, 1): 0, (0.4, 19, 2): 0, (0.4, 19, 3): 0, (0.4, 19, 4): 0, (0.4, 20, 1): 0, (0.4, 20, 2): 0, (0.4, 20, 3): 0, (0.4, 20, 4): 0, (0.4, 21, 1): 0, (0.4, 21, 2): 0, (0.4, 21, 3): 0, (0.4, 21, 4): 0, (0.4, 22, 1): 0, (0.4, 22, 2): 0, (0.4, 22, 3): 0, (0.4, 22, 4): 0, (0.4, 23, 1): 0, (0.4, 23, 2): 0, (0.4, 23, 3): 0, (0.4, 23, 4): 0, (0.6, 1, 1): 0, (0.6, 1, 2): 0, (0.6, 1, 3): 0, (0.6, 1, 4): 0, (0.6, 2, 1): 0, (0.6, 2, 2): 0, (0.6, 2, 3): 0, (0.6, 2, 4): 0, (0.6, 3, 1): 0, (0.6, 3, 2): 0, (0.6, 3, 3): 0, (0.6, 3, 4): 0, (0.6, 4, 1): 0, (0.6, 4, 2): 0, (0.6, 4, 3): 0, (0.6, 4, 4): 0, (0.6, 5, 1): 0, (0.6, 5, 2): 0, (0.6, 5, 3): 0, (0.6, 5, 4): 0, (0.6, 6, 1): 0, (0.6, 6, 2): 0, (0.6, 6, 3): 0, (0.6, 6, 4): 0, (0.6, 7, 1): 0, (0.6, 7, 2): 0, (0.6, 7, 3): 0, (0.6, 7, 4): 0, (0.6, 8, 1): 0, (0.6, 8, 2): 0, (0.6, 8, 3): 0, (0.6, 8, 4): 0, (0.6, 9, 1): 0, (0.6, 9, 2): 0, (0.6, 9, 3): 0, (0.6, 9, 4): 0, (0.6, 10, 1): 0, (0.6, 10, 2): 0, (0.6, 10, 3): 0, (0.6, 10, 4): 0, (0.6, 11, 1): 0, (0.6, 11, 2): 0, (0.6, 11, 3): 0, (0.6, 11, 4): 0, (0.6, 12, 1): 0, (0.6, 12, 2): 0, (0.6, 12, 3): 0, (0.6, 12, 4): 0, (0.6, 13, 1): 0, (0.6, 13, 2): 0, (0.6, 13, 3): 0, (0.6, 13, 4): 0, (0.6, 14, 1): 0, (0.6, 14, 2): 0, (0.6, 14, 3): 0, (0.6, 14, 4): 0, (0.6, 15, 1): 0, (0.6, 15, 2): 0, (0.6, 15, 3): 0, (0.6, 15, 4): 0, (0.6, 16, 1): 0, (0.6, 16, 2): 0, (0.6, 16, 3): 0, (0.6, 16, 4): 0, (0.6, 17, 1): 0, (0.6, 17, 2): 0, (0.6, 17, 3): 0, (0.6, 17, 4): 0, (0.6, 18, 1): 0, (0.6, 18, 2): 0, (0.6, 18, 3): 0, (0.6, 18, 4): 0, (0.6, 19, 1): 0, (0.6, 19, 2): 0, (0.6, 19, 3): 0, (0.6, 19, 4): 0, (0.6, 20, 1): 0, (0.6, 20, 2): 0, (0.6, 20, 3): 0, (0.6, 20, 4): 0, (0.6, 21, 1): 0, (0.6, 21, 2): 0, (0.6, 21, 3): 0, (0.6, 21, 4): 0, (0.6, 22, 1): 0, (0.6, 22, 2): 0, (0.6, 22, 3): 0, (0.6, 22, 4): 0, (0.6, 23, 1): 0, (0.6, 23, 2): 0, (0.6, 23, 3): 0, (0.6, 23, 4): 0, (0.8, 1, 1): 0, (0.8, 1, 2): 0, (0.8, 1, 3): 0, (0.8, 1, 4): 0, (0.8, 2, 1): 0, (0.8, 2, 2): 0, (0.8, 2, 3): 0, (0.8, 2, 4): 0, (0.8, 3, 1): 0, (0.8, 3, 2): 0, (0.8, 3, 3): 0, (0.8, 3, 4): 0, (0.8, 4, 1): 0, (0.8, 4, 2): 0, (0.8, 4, 3): 0, (0.8, 4, 4): 0, (0.8, 5, 1): 0, (0.8, 5, 2): 0, (0.8, 5, 3): 0, (0.8, 5, 4): 0, (0.8, 6, 1): 0, (0.8, 6, 2): 0, (0.8, 6, 3): 0, (0.8, 6, 4): 0, (0.8, 7, 1): 0, (0.8, 7, 2): 0, (0.8, 7, 3): 0, (0.8, 7, 4): 0, (0.8, 8, 1): 0, (0.8, 8, 2): 0, (0.8, 8, 3): 0, (0.8, 8, 4): 0, (0.8, 9, 1): 0, (0.8, 9, 2): 0, (0.8, 9, 3): 0, (0.8, 9, 4): 0, (0.8, 10, 1): 0, (0.8, 10, 2): 0, (0.8, 10, 3): 0, (0.8, 10, 4): 0, (0.8, 11, 1): 0, (0.8, 11, 2): 0, (0.8, 11, 3): 0, (0.8, 11, 4): 0, (0.8, 12, 1): 0, (0.8, 12, 2): 0, (0.8, 12, 3): 0, (0.8, 12, 4): 0, (0.8, 13, 1): 0, (0.8, 13, 2): 0, (0.8, 13, 3): 0, (0.8, 13, 4): 0, (0.8, 14, 1): 0, (0.8, 14, 2): 0, (0.8, 14, 3): 0, (0.8, 14, 4): 0, (0.8, 15, 1): 0, (0.8, 15, 2): 0, (0.8, 15, 3): 0, (0.8, 15, 4): 0, (0.8, 16, 1): 0, (0.8, 16, 2): 0, (0.8, 16, 3): 0, (0.8, 16, 4): 0, (0.8, 17, 1): 0, (0.8, 17, 2): 0, (0.8, 17, 3): 0, (0.8, 17, 4): 0, (0.8, 18, 1): 0, (0.8, 18, 2): 0, (0.8, 18, 3): 0, (0.8, 18, 4): 0, (0.8, 19, 1): 0, (0.8, 19, 2): 0, (0.8, 19, 3): 0, (0.8, 19, 4): 0, (0.8, 20, 1): 0, (0.8, 20, 2): 0, (0.8, 20, 3): 0, (0.8, 20, 4): 0, (0.8, 21, 1): 0, (0.8, 21, 2): 0, (0.8, 21, 3): 0, (0.8, 21, 4): 0, (0.8, 22, 1): 0, (0.8, 22, 2): 0, (0.8, 22, 3): 0, (0.8, 22, 4): 0, (0.8, 23, 1): 0, (0.8, 23, 2): 0, (0.8, 23, 3): 0, (0.8, 23, 4): 0, (1, 1, 1): 0, (1, 1, 2): 0, (1, 1, 3): 0, (1, 1, 4): 0, (1, 2, 1): 0, (1, 2, 2): 0, (1, 2, 3): 0, (1, 2, 4): 0, (1, 3, 1): 0, (1, 3, 2): 0, (1, 3, 3): 0, (1, 3, 4): 0, (1, 4, 1): 0, (1, 4, 2): 0, (1, 4, 3): 0, (1, 4, 4): 0, (1, 5, 1): 0, (1, 5, 2): 0, (1, 5, 3): 0, (1, 5, 4): 0, (1, 6, 1): 0, (1, 6, 2): 0, (1, 6, 3): 0, (1, 6, 4): 0, (1, 7, 1): 0, (1, 7, 2): 0, (1, 7, 3): 0, (1, 7, 4): 0, (1, 8, 1): 0, (1, 8, 2): 0, (1, 8, 3): 0, (1, 8, 4): 0, (1, 9, 1): 0, (1, 9, 2): 0, (1, 9, 3): 0, (1, 9, 4): 0, (1, 10, 1): 0, (1, 10, 2): 0, (1, 10, 3): 0, (1, 10, 4): 0, (1, 11, 1): 0, (1, 11, 2): 0, (1, 11, 3): 0, (1, 11, 4): 0, (1, 12, 1): 0, (1, 12, 2): 0, (1, 12, 3): 0, (1, 12, 4): 0, (1, 13, 1): 0, (1, 13, 2): 0, (1, 13, 3): 0, (1, 13, 4): 0, (1, 14, 1): 0, (1, 14, 2): 0, (1, 14, 3): 0, (1, 14, 4): 0, (1, 15, 1): 0, (1, 15, 2): 0, (1, 15, 3): 0, (1, 15, 4): 0, (1, 16, 1): 0, (1, 16, 2): 0, (1, 16, 3): 0, (1, 16, 4): 0, (1, 17, 1): 0, (1, 17, 2): 0, (1, 17, 3): 0, (1, 17, 4): 0, (1, 18, 1): 0, (1, 18, 2): 0, (1, 18, 3): 0, (1, 18, 4): 0, (1, 19, 1): 0, (1, 19, 2): 0, (1, 19, 3): 0, (1, 19, 4): 0, (1, 20, 1): 0, (1, 20, 2): 0, (1, 20, 3): 0, (1, 20, 4): 0, (1, 21, 1): 0, (1, 21, 2): 0, (1, 21, 3): 0, (1, 21, 4): 0, (1, 22, 1): 0, (1, 22, 2): 0, (1, 22, 3): 0, (1, 22, 4): 0, (1, 23, 1): 0, (1, 23, 2): 0, (1, 23, 3): 0, (1, 23, 4): 0}

In [41]:
def find_min_diff(wish_time, allocate_time):

    diff = min(abs(wish_time - allocate_time), abs(allocate_time - wish_time + 24))

    return diff

11

In [46]:
def convert_percentage(num):
    if num <= 0.2:
        return "20%"
    elif num <= 0.4:
        return "40%"
    elif num <= 0.6:
        return "60%"
    elif num <= 0.8:
        return "80%"
    else:
        return "100%"
        # 將 0~100 等分為五份，分別為 20, 40, 60, 80, 100
        rounded = round(percentage / 20) * 20
        return str(rounded) + "%"

In [50]:


user_history_perf = pd.read_csv('Dataset/user_history_preference.csv', index_col=0)

with open('user_facility_perc_dic.json') as f:
    user_facility_perc_dic = json.load(f)


with open('q_table.json') as f:
    q_table = json.load(f)

with open("output.txt", "w") as f:
    for row in user_history_perf.itertuples():
        userId = row.userId
        facilityType = row.facilityType
        createdHour = row.createdHour
        try:
            user_facility_percent_list = user_facility_perc_dic[userId]
            if facilityType in [int(f_type) for f_type in user_facility_percent_list.keys()]:
                user_facility_perf = user_facility_perc_dic[str(userId)][str(facilityType)]
                for time in range(24):
                    min_diff = find_min_diff(createdHour, time)
                    percentage = convert_percentage(user_facility_perf)
                    f.write(f"{percentage}, {min_diff}, {facilityType}\n")
                
        except KeyError:
            print("Error: 'key1' not found in JSON file")

In [35]:
import pandas as pd
import time
request_df = pd.read_csv("Dataset/charging_data_2_move.csv")
# print(request_df)
for item in request_df.iterrows():
        request = list(item[1][["_id", "userId", "chargingHour", "createdHour", "locationId"]])
        print(request)

KeyError: "['chargingHour'] not in index"